### PR TITLE
Update rli_raid.class.php

### PR DESCRIPTION
**Pull request by rswiders**
Correct raid times when server is not using GMT

### CODE REVIEW

**Comment by GodMod** [comment]
To be honest, there is no difference between these calls. date_for_user() is the same as user_date(), only with the difference, that you can give date_for_user() an UserID.

**Comment by rswiders** [comment]
Am I looking at the two functions wrong? When using user_date() the code just determines a format string and then returns a date based on that format string. In date_for_user() the code does the same, however before returning the date it sets the timezone based on the timezone it gets for the user. This will make the two functions return a different result if the user timezone isn't GMT.

**Comment by GodMod** [comment]
user_date() uses the timezone of the current user. Therefore both should return the same time. If not, there is a bug at the implementation

**Comment by GodMod** [comment]
Yeah, I have a bug at the implementation. Therefore both do not return the same date for the same user.

**Pull request closed without merging**
